# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.migrated.updateDir", true);
user_pref("browser.EULA.3.accepted", true);
user_pref("browser.EULA.override", true);
user_pref("browser.allowpopups", true);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.link.open_external", 2);
user_pref("browser.link.open_newwindow", 2);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.offline", false);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.search.update", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20141105223254");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 2519);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage", "chrome://src/content/RemoteRunner.html?sessionId=6783cd56a5904b48aca2830a2312382f&multiWindow=true&baseUrl=http%3A%2F%2Flocalhost%2Fblog%2Findex-test.php%2F&debugMode=false&driverUrl=http://localhost:4444/selenium-server/driver/");
user_pref("browser.startup.homepage_override.buildID", "20141105223254");
user_pref("browser.startup.homepage_override.mstone", "33.0.3");
user_pref("browser.taskbar.lastgroupid", "1ADF46625062D2C5");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-call-button\",\"social-share-button\",\"greasemonkey-tbb\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":0,\"newElementCount\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1415716706799");
user_pref("datareporting.policy.firstRunTime", "1415630306798");
user_pref("datareporting.sessions.current.activeTicks", 7);
user_pref("datareporting.sessions.current.firstPaint", 2146);
user_pref("datareporting.sessions.current.main", 188);
user_pref("datareporting.sessions.current.sessionRestored", 2304);
user_pref("datareporting.sessions.current.startTime", "1415887693331");
user_pref("datareporting.sessions.current.totalTime", 32);
user_pref("datareporting.sessions.currentIndex", 4);
user_pref("datareporting.sessions.previous.0", "{\"s\":1415630305927,\"a\":0,\"t\":2,\"c\":true,\"m\":188,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1415630309329,\"a\":6,\"t\":30,\"c\":true,\"m\":141,\"fp\":2193,\"sr\":3114}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1415630341712,\"a\":5,\"t\":28,\"c\":false,\"m\":4,\"fp\":2060,\"sr\":2922}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1415887690935,\"a\":0,\"t\":1,\"c\":true,\"m\":172,\"fp\":-1,\"sr\":-1}");
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_SCRATCHPAD_OPENED_PER_USER_FLAG\":\"33.0.3\"}");
user_pref("dom.disable_open_during_load", false);
user_pref("dom.max_chrome_script_run_time", 1800);
user_pref("dom.max_script_run_time", 1800);
user_pref("extensions.autoDisableScopes", 10);
user_pref("extensions.blocklist.enabled", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "readystate%40openqa.org:1.0,%7B503A0CD4-EDC8-489b-853B-19E0BAA8F0A4%7D:1.0,%7B538F0036-F358-4f84-A764-89FB437166B4%7D:1.0,%7Be4a8a97b-f2ed-450b-b12d-ee082ba24781%7D:2.3,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:33.0.3");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.greasemonkey.haveInsertedToolbarbutton", true);
user_pref("extensions.greasemonkey.newscript_namespace", "reSetAlert");
user_pref("extensions.greasemonkey.stats.prompted", true);
user_pref("extensions.greasemonkey.version", "2.3");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files\\\\SoftDir\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1415543133618,\"rdfTime\":1415262897000}}},{\"name\":\"app-profile\",\"addons\":{\"readystate@openqa.org\":{\"descriptor\":\"C:\\\\Users\\\\ADMINI~1\\\\AppData\\\\Local\\\\Temp\\\\customProfileDir6783cd56a5904b48aca2830a2312382f\\\\extensions\\\\readystate@openqa.org\",\"mtime\":1415887690768,\"rdfTime\":1415887690768},\"{503A0CD4-EDC8-489b-853B-19E0BAA8F0A4}\":{\"descriptor\":\"C:\\\\Users\\\\ADMINI~1\\\\AppData\\\\Local\\\\Temp\\\\customProfileDir6783cd56a5904b48aca2830a2312382f\\\\extensions\\\\{503A0CD4-EDC8-489b-853B-19E0BAA8F0A4}\",\"mtime\":1415887690878,\"rdfTime\":1415887690768},\"{538F0036-F358-4f84-A764-89FB437166B4}\":{\"descriptor\":\"C:\\\\Users\\\\ADMINI~1\\\\AppData\\\\Local\\\\Temp\\\\customProfileDir6783cd56a5904b48aca2830a2312382f\\\\extensions\\\\{538F0036-F358-4f84-A764-89FB437166B4}\",\"mtime\":1415887690784,\"rdfTime\":1415887690784},\"{e4a8a97b-f2ed-450b-b12d-ee082ba24781}\":{\"descriptor\":\"C:\\\\Users\\\\ADMINI~1\\\\AppData\\\\Local\\\\Temp\\\\customProfileDir6783cd56a5904b48aca2830a2312382f\\\\extensions\\\\{e4a8a97b-f2ed-450b-b12d-ee082ba24781}.xpi\",\"mtime\":1415887690472}}}]");
user_pref("extensions.lastAppVersion", "33.0.3");
user_pref("extensions.lastPlatformVersion", "33.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://search/Greasemonkey");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.update.enabled", false);
user_pref("gecko.buildID", "20141105223254");
user_pref("gecko.mstone", "33.0.3");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.http.phishy-userpass-length", 255);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 52594);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.warn_entering_secure", false);
user_pref("security.warn_entering_secure.show_once", false);
user_pref("security.warn_entering_weak", false);
user_pref("security.warn_entering_weak.show_once", false);
user_pref("security.warn_leaving_secure", false);
user_pref("security.warn_leaving_secure.show_once", false);
user_pref("security.warn_submit_insecure", false);
user_pref("security.warn_submit_insecure.show_once", false);
user_pref("security.warn_viewing_mixed", false);
user_pref("security.warn_viewing_mixed.show_once", false);
user_pref("signon.importedFromSqlite", true);
user_pref("signon.rememberSignons", false);
user_pref("startup.homepage_override_url", "chrome://src/content/RemoteRunner.html?sessionId=6783cd56a5904b48aca2830a2312382f&multiWindow=true&baseUrl=http%3A%2F%2Flocalhost%2Fblog%2Findex-test.php%2F&debugMode=false&driverUrl=http://localhost:4444/selenium-server/driver/");
user_pref("startup.homepage_welcome_url", "");
user_pref("toolkit.networkmanager.disable", true);
user_pref("toolkit.startup.last_success", 1415887693);
user_pref("toolkit.telemetry.previousBuildID", "20141105223254");
