CREATE TABLE IF NOT EXISTS `target` (
  `target_id` int(11) NOT NULL AUTO_INCREMENT,
  `target_taobao_id` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `xuetongneilicaizhi` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `xuetongcaizhi` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `shangshinianfenjijie` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `fengge` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `bangmiancaizhi` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `xuemianneilicaizhi` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `pizhitezhi` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `xiedicaizhi` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `xuekuanpingming` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `tonggao` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `xietongkuanshi` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `genggao` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `xiegengkuanshi` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `bihefangshi` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `liuxingyuansu` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `zhizhuogongyi` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `tuan` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `shehejijie` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `target_taobao_title1` varchar(128) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `target_taobao_title2` varchar(128) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `target_taobao_title3` varchar(128) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `target_taobao_sku` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `target_go2_sku` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `target_title_search` int(1) NOT NULL,
  `target_title_used` int(1) NOT NULL,
  `source_taobao_id1` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `source_taobao_id2` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `source_taobao_id3` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `source_taobao_keyword1` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `source_taobao_keyword2` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `source_taobao_keyword3` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`target_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=13 ;